#!/bin/sh

#!/bin/sh

# Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

bspc config border_width        3
bspc config window_gap          6
bspc config top_padding         0

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
#bspc config history_aware_focus         true

bspc monitor --reset-desktops term www dev chat edit play virt 8 9 10

# Use monocle layout on desktop 1
bspc desktop '^1' --layout monocle

# Script for external rules
bspc config external_rules_command "$BSPWM_CONFIG/scripts/external_rules"

# Send to www desktop
bspc rule --add surf                     desktop='www' follow=on

# Colors
bspc config focused_border_color            "#88C0D0"
bspc config active_border_color             "#81A1C1"
bspc config normal_border_color             "#5E81AC"
#bspc config urgent_border_color             "$blue"
bspc config presel_feedback_color           "#EBCB8B"
#bspc config focused_locked_border_color     "$brightred"
#bspc config active_locked_border_color      "$red"
#bspc config normal_locked_border_color      "$black"
#bspc config focused_sticky_border_color     "$brightcyan"
#bspc config active_sticky_border_color      "$cyan"
#bspc config normal_sticky_border_color      "$black"
#bspc config focused_private_border_color    "$brightblue"
#bspc config active_private_border_color     "$blue"
#bspc config normal_private_border_color     "$black"

setbg &

# Load session
export BSPWM_STATE="${XDG_DATA_HOME:-$HOME/.local/share}/bspwm-state.json"
if [ -e "$BSPWM_STATE" ] ; then
	bspc wm --load-state "$BSPWM_STATE"
	bspc wm --adopt-orphans
	rm "$BSPWM_STATE"
fi

# Read panel configuration and launch it
. "${XDG_CONFIG_HOME:-$HOME/.config}/lemonbar/panel.cfg" && ~/.local/bin/wm/panel \
    | lemonbar -a 50 -g "${BARWIDTH}x${BARHEIGHT}+${EDGEWIDTH}+${EDGEWIDTH}" \
    -f "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" \
    -u "$UNDERLINE_WIDTH" | sh &
